version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: weather-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'

volumes:
  postgres_data: